### ISSUE TITLE
semillas 

### ISSUE THREAD

**Issue by fprebolledo** [IIC2513-2019-1/my-university#1]
No entiendo como usar las semillas que están en la carpeta seeds o como subirlas a la base para poder usar los datos en la app.

**Comment by gpvidal** [comment]
Hola @francisca1 !

Las seeds son datos que nos permiten poblar la base de datos, ya sea porque la tuvimos que borrar para hacer una prueba, estamos haciendo una instalación desde cero, etc.

Cuando creas un modelo, automáticamente se te crea un archivo para que puedas tus *seeds*. Por ejemplo, cuando creamos el modelo de cursos en este proyecto se agregó [este archivo](https://github.com/IIC2513-2019-1/my-university/blob/dev/src/seeds/20190402015933-add-courses.js) que completamos con información de cursos.

Luego, para agregar las seeds tenemos que correrlas con este comando:

```sh
$ ./node_modules/.bin/sequelize db:seeds:all
```

Y esto cargará todos los datos.

Saludos,

**Comment by Javierdr** [comment]
Profesor @gpvidal,
 el comando para correr las seeds es 
`$ ./node_modules/.bin/sequelize db:seed:all` sin la "s" en el seed. 

Saludos.

**Comment by gpvidal** [comment]
Gracias!
